name: "Deploy Helm Chart to K8S"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update deployment
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade pacman ./charts/pacman/ --install --atomic --namespace=ns-pacman
          kubeconfig: '${{ secrets.K8S_CONFIG }}'
          overrule_existing_kubeconfig: "true"

      - name: send result to telegram
        uses: robotomize/notify-telegram@v0.1.0
        with:
          chat: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          status: ${{ job.status }}