name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: get-npm-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: package-version
      with:
        path: src

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: type=semver,pattern={{version}},value=${{ steps.package-version.outputs.current-version}}

    - name: Build and push Docker image
      id: build-data
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: send result to tg
      uses: robotomize/notify-telegram@v0.1.0
      with:
        chat: ${{ secrets.TG_CHAT_ID }} # user id or channel name secret
        token: ${{ secrets.TG_BOT_TOKEN }} # token secret
        status: ${{ job.status }} # do not modify this line
        message: ${{ steps.build-data.outputs.metadata}}
